version: "3.7"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DHPARAM_GENERATION=false
    networks:
      - reverse_proxy

  nginx-proxy-acme:
    container_name: nginx-acme
    image: nginxproxy/acme-companion
    volumes:
      - ./nginx/acme:/etc/acme.sh
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/.htpasswd:/etc/apache2/.htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${CERTIFICATE_OWNER_EMAIL}
      - "ACME_CA_URI=${ACME_CA_URI:-https://acme-v02.api.letsencrypt.org/directory}"
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    name: reverse_proxy
